### ISSUE TITLE
Unicorn2 TODO

### ISSUE THREAD

**Issue by wtdcode** [unicorn-engine/unicorn#1449]
Hello everyone.

I feel quite excited about the Unicorn2 beta release. But before an official release, I have some urgent TODO left.

- [ ] Rust bindings improvement. This includes: Refactor in design && Build scripts && Publishi to crates.io
- [ ] Python bindings publish.
- [ ] Improvement for other bindings. Sorry I'm no familiar with every language.
- [ ] Issue/PR template.

and so on...

I'm not familiar with everything in Unicorn2, especially the bindings in other languages. Look forward to your contribution!

By the way, if you feel your issue/pr wrongly closed, simply re-open it and I would have a look.

**Comment by wtdcode** [comment]
I close all issues prior to 2020-01-01, if any one feels his issue closed wrongly, please simply re-open.

**Comment by bet4it** [comment]
Issue closed by you can't be reopened by the author🙄

**Comment by abebeos** [comment]
@wtdcode, isn't this already been elegantly tracked within https://github.com/unicorn-engine/unicorn/milestone/1 ?

**Comment by wtdcode** [comment]
> https://github.com/unicorn-engine/unicorn/milestone/1

Yes, this issue is out-of-date exactly.

**Comment by abebeos** [comment]
Ok (remember that you can add a description to milestones, too).
